using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace TTT_Practice.Models
{
    public partial class TblCustomerSetup
    {
        public int CtintCustomerSetupId { get; set; }
        public int? CtintHoldingCompanyId { get; set; }
        public string CtstrCustomerAccount { get; set; }
        public string CtstrCustomerAlternateAcct { get; set; }
        public string CtstrCustomerId { get; set; }
        public string CtsrtCustomerType { get; set; }
        public string CtsrtCustomerSort1 { get; set; }
        public string CtsrtCustomerSort2 { get; set; }
        public int? CtintInstitutionType { get; set; }
        public bool GeneralInfo { get; set; }
        public string CtstrCustomerName1 { get; set; }
        public string CtstrCustomerName2 { get; set; }
        public string CtstrStreetAddress1 { get; set; }
        public string CtstrStreetAddress2 { get; set; }
        public string CtstrStreetAddress3 { get; set; }
        public string CtstrCity { get; set; }
        public string CtstrState { get; set; }
        public string CtstrZipCode { get; set; }
        public string CtstrTelephone { get; set; }
        public string CtstrFax { get; set; }
        public string CtstrModem { get; set; }
        public string CtstrEmail { get; set; }
        public DateTime? CtdateOpened { get; set; }
        public DateTime? CtdateUpdated { get; set; }
        public bool ProcessingRequired { get; set; }
        public bool? CtboolProcessAccounting { get; set; }
        public bool CtboolProcessSafekeeping { get; set; }
        public bool CtboolTrading { get; set; }
        public bool CtboolExport1099 { get; set; }
        public bool CtboolSweepDaily { get; set; }
        public int? CtintBillingId { get; set; }
        public bool TaxationInformation { get; set; }
        public string CtstrTaxId { get; set; }
        public string CtstrTaxId1 { get; set; }
        public string CtstrTaxId2 { get; set; }
        public bool CtboolAlternateMinTaxMthd { get; set; }
        public float? CtdblStateTax { get; set; }
        public float? CtdblFederalTaxRate { get; set; }
        public bool CtboolEle171c { get; set; }
        public DateTime? CtdateEld171c { get; set; }
        public bool CtboolEle1278b1 { get; set; }
        public DateTime? CtdateEld1278b1 { get; set; }
        public bool CtboolDealer475 { get; set; }
        public bool CtboolFinancialInstitution { get; set; }
        public bool Compliance { get; set; }
        public bool CtboolCorporateResolutionOnFile { get; set; }
        public bool CtboolW9onFile { get; set; }
        public string CtstrRegisteredRep { get; set; }
        public bool? CtboolClassBsecurities { get; set; }
        public int? CtintComissionId { get; set; }
        public float? CtdblCostOfFunds { get; set; }
        public bool Regulatory { get; set; }
        public string CtstrCertificateNumber { get; set; }
        public string CtstrAbanumber { get; set; }
        public string CtstrFhlbnumber { get; set; }
        public string CtstrOccnumber { get; set; }
        public string CtstrOfficeOfFinanceNumber { get; set; }
        public string CtstrFdicnumber { get; set; }
        public bool CtboolNationallyChartered { get; set; }
        public bool CtboolStateChartered { get; set; }
        public decimal? CtcurAssetSize { get; set; }
        public bool CtboolHasForeignOffice { get; set; }
        public bool AccountingDefaults { get; set; }
        public short? CtintMonthOfFiscalYearEnd { get; set; }
        public int? CtintAccountingMethodBul { get; set; }
        public int? CtintAccountingMethodMbs { get; set; }
        public int? CtintAccountingMethodCmo { get; set; }
        public int? CtintAccountingSpeedMbs { get; set; }
        public int? CtintAccountingSpeedCmo { get; set; }
        public int? CtintSpeedUnitMbs { get; set; }
        public int? CtintSpeedUnitCmo { get; set; }
        public double? CtdblSpeedValueMbs { get; set; }
        public double? CtdblSpeedValueCmo { get; set; }
        public int? CtintAccountingArmmethodId { get; set; }
        public int? CtintFeeAmortizationMethodId { get; set; }
        public bool CtboolCashMethod { get; set; }
        public string CtstrDefaultFas115 { get; set; }
        public DateTime? CtdateStartFas133 { get; set; }
        public short? CtintPostFrequencyFas133 { get; set; }
        public int? CtintHolidayListIdfas133 { get; set; }
        public bool? PaymentDeliveryDefault { get; set; }
        public string CtstrDdaaccount { get; set; }
        public string CtstrClearingAccount { get; set; }
        public decimal? CtsngCurrentBalanceDda { get; set; }
        public decimal? CtsngAvailableBalanceDda { get; set; }
        public string CtstrElectronicFundsTransfer { get; set; }
        public string CtstrPurchPmtInstructionsId { get; set; }
        public string CtstrPurchSafekeepingLocationId { get; set; }
        public bool CreditRisk { get; set; }
        public DateTime? CtdateLastCreditRatingUpdate { get; set; }
        public decimal? CtcurTier1Capital { get; set; }
        public decimal? CtcurTradeLimit { get; set; }
        public decimal? CtcurCreditLimit { get; set; }
        public decimal? CtcurExposureLimit { get; set; }
        public string CtstrCreditRatingOofid { get; set; }
        public string CtstrThomsonBankWatch { get; set; }
        public string CtstrIbcaindividualRating { get; set; }
        public string CtstrIbcacountryRating { get; set; }
        public bool CreditRating { get; set; }
        public string CtstrMoodyComercialPaper { get; set; }
        public string CtstrMoodyDepositsShortTerm { get; set; }
        public string CtstrMoodyDepositsLongTerm { get; set; }
        public string CtstrMoodySeniorDebt { get; set; }
        public string CtstrMoodyFmpshortTerm { get; set; }
        public string CtstrMoodyFmplongTerm { get; set; }
        public string CtstrStdPoorShortTermRating { get; set; }
        public string CtstrStdPoorDepositsShortTerm { get; set; }
        public string CtstrStdPoorDepositsLongTerm { get; set; }
        public string CtstrStdPoorSeniorDebt { get; set; }
        public string CtstrStdPoorFmpshortTerm { get; set; }
        public string CtstrStdPoorFmplongTerm { get; set; }
        public bool BuyingHabits { get; set; }
        public bool CtboolHabitBuyAbs { get; set; }
        public bool CtboolHabitCmo { get; set; }
        public bool CtboolHabitPremiumCmo { get; set; }
        public bool CtboolHabitDiscountsCmo { get; set; }
        public bool CtboolHabitAgencyCmo { get; set; }
        public bool CtboolHabitMbs { get; set; }
        public bool CtboolHabitPremiumMbs { get; set; }
        public bool CtboolHabitDiscountMbs { get; set; }
        public bool CtboolHabitCurCpnMbs { get; set; }
        public bool CtboolHabitNewProductionMbs { get; set; }
        public bool CtboolHabitMidAgeMbs { get; set; }
        public bool CtboolHabitSeasonedMbs { get; set; }
        public bool CtboolVrmmbs { get; set; }
        public string CtstrVrmindexId { get; set; }
        public double? CtsngReturnOnMbs { get; set; }
        public bool CtboolPremiumGen { get; set; }
        public bool CtboolDiscountGen { get; set; }
        public bool CtboolCallablesGen { get; set; }
        public bool CtboolStructuredGen { get; set; }
        public bool CtboolFloaterGen { get; set; }
        public bool CtboolDurationMatch { get; set; }
        public double? CtsngDurMin { get; set; }
        public double? CtsngDurMax { get; set; }
        public double? CtsngMinMaturity { get; set; }
        public bool SwapsDefaults { get; set; }
        public double? TefraPenalty { get; set; }
        public DateTime? CtdateSwapSettlement { get; set; }
        public DateTime? CtdateSwapHorizon { get; set; }
        public DateTime? CtdateSwapAsOf { get; set; }
        public string CtstrTaxBook { get; set; }
        public double? CtsngCapitalCost { get; set; }
        public decimal? CtcurCapitalAmount { get; set; }
        public string CtstrProfitabilityId { get; set; }
        public string CtstrUserDef01 { get; set; }
        public bool PricingVendorDefaults { get; set; }
        public string CtstrPricingDefaultSourceBulid { get; set; }
        public string CtstrPricingDefaultSourceMbsid { get; set; }
        public string CtstrPricingDefaultSourceCmoid { get; set; }
        public bool? DataFeeds { get; set; }
        public bool CtboolDiscountNoteFeedInto { get; set; }
        public byte? VisibleId { get; set; }
        public byte? ProcessableId { get; set; }
        public byte? ReportableId { get; set; }
        public string SLastUpdateId { get; set; }
        public DateTime? DtLastUpdateDt { get; set; }
        public short? IConcurrencyId { get; set; }
        public DateTime? TermDt { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateDt { get; set; }
        public string ModifyUser { get; set; }
        public DateTime? ModifyDt { get; set; }
        public double? CtdblReInvestRate { get; set; }
        public int? CtintPricingDay { get; set; }
        public bool? CtbitGainOnCalls { get; set; }
        public string CtstrCompanyNumber { get; set; }
        public string CtstrDefaultCostCenter { get; set; }
        public int CtintChartOfAccountId { get; set; }
        public int? CtintCurrencyId { get; set; }
        public int? CtintTradeActivityTypeId { get; set; }
        public bool CtbitUseCallNotice { get; set; }
        public bool? CtbitLossOnCalls { get; set; }
        public bool? CtboolCustomerAdviceEmail { get; set; }
        public bool? CtboolCustomerAdviceFax { get; set; }
        public bool? CtboolCustomerAdviceMail { get; set; }
        public int? CtlBillingCycle { get; set; }
        public DateTime? CtsdtBillingStartDate { get; set; }
        public bool? CtboolBillingByHoldingCompany { get; set; }
        public int Delivery { get; set; }
        public string CtstrDtcParticipantNumber { get; set; }
        public string CtstrDtcInstitutionalNumber { get; set; }
        public string CtstrDtcAgentBankNumber { get; set; }
        public string CtstrChipsCd { get; set; }
        public string CtstrSwiftCd { get; set; }
        public string CtstrUidCd { get; set; }
        public string CtstrBicCd { get; set; }
        public byte CtintAmortizeToDateId { get; set; }
        public string CtstrIdcrating { get; set; }
        public string CtstrPaymentDelivery { get; set; }
        public bool? CtboolRfconservative { get; set; }
        public bool? CtboolRflow { get; set; }
        public bool? CtboolSwapLiability { get; set; }
        public decimal? CtmnyAnnualIncomeMin { get; set; }
        public int? CtlTaxStatusId { get; set; }
        public int? CtlInitialFundsSourceId { get; set; }
        public bool? CtboolemployeeofBf { get; set; }
        public bool? CtboolemployeeofBbtorI { get; set; }
        public bool? CtboolRfhighRisk { get; set; }
        public bool? CtboolRfspeculation { get; set; }
        public bool? CtboolRfmoderate { get; set; }
        public bool? CtboolIoshortTerm { get; set; }
        public bool? CtboolIolongTerm { get; set; }
        public bool? CtboolIoincome { get; set; }
        public int? CtintBranchId { get; set; }
        public int? CtintDivisionId { get; set; }
        public int? CtintBankRelationshipManagerId { get; set; }
        public int? CtintBankCostCenterId { get; set; }
        public decimal? CtmnyNetWorthMax { get; set; }
        public decimal? CtmnyNetWorthMin { get; set; }
        public decimal? CtmnyAnnualIncomeMax { get; set; }
        public int? CtintRegionId { get; set; }
        public bool? CtboolW8reqd { get; set; }
        public bool? CtboolReqdByLaw1099Flag { get; set; }
        public int? CtintCountryId { get; set; }
        public int CtintConstraintBookPrice { get; set; }
        public short CtintFeeAmortEndDateId { get; set; }
        public byte CtintClearingAccountTypeId { get; set; }
        public int CtintConstraintBookPriceMbs { get; set; }
        public int CtintConstraintBookPriceCmo { get; set; }
        public int CtintConstraintBookPricePortfolio { get; set; }
        public string CtstrReferredBy { get; set; }
        public decimal CtcurIbtfee { get; set; }
        public string CtstrNotes { get; set; }
        public string CtstrBankRepCostCenter { get; set; }
        public string CtstrResponsibleCostCenter { get; set; }
        public string CtstrSavingsAcct { get; set; }
        public string CtstrSubAccount { get; set; }
        public string CtstrBankRep { get; set; }
        public bool Ctbool1099HardCopy { get; set; }
        public bool CtboolRepoAgreement { get; set; }
        public bool CtboolRollover { get; set; }
        public bool CtboolW9exempt { get; set; }
        public int CtintFeeAmortizationMethod { get; set; }
        public bool CtboolUseMarketProjection { get; set; }
        public bool CtboolUseCleanUpCall { get; set; }
        public bool CtboolDonotRepriceInPurchaseMonth { get; set; }
        public decimal? CtmnyExposure { get; set; }
        public bool CtboolIsda { get; set; }
        public decimal? CtmnyActualCollateral { get; set; }
        public decimal? CtmnySecuredLimit { get; set; }
        public bool? CtboolMonitorLimit { get; set; }
        public bool CtboolPrintHardcopyOnly { get; set; }
        public bool CtboolCreatePmtAdvice { get; set; }
        public bool CtboolCreateCustStatements { get; set; }
        public bool CtboolCreateConfirmations { get; set; }
        public bool CtblnAccountForms { get; set; }
        public byte? CttnyAccountingPeriodStartDay { get; set; }
        public int? CtlCommissionTierId { get; set; }
        public decimal? CtmnyMinFee { get; set; }
        public decimal? CtmnyAccountFee { get; set; }
        public decimal? CtmnyStatementFee { get; set; }
        public decimal? CtmnyAmountPurchased { get; set; }
        public double? CtdblAdjPercentage { get; set; }
        public bool CtboolDeferredBilling { get; set; }
        public int? CtintHoldingFeeId { get; set; }
        public string CtstrNcuanumber { get; set; }
        public string CtstrNaicnumber { get; set; }
        public int? CtintMarginMatrix { get; set; }
        public int? CtintFeeGroupId { get; set; }
        public int? CtintCollateralBucketId { get; set; }
        public int? CtintNonTransFeeGroup { get; set; }
        public bool CtboolUseRepoBalanceCalc { get; set; }
        public double? CtdblSwapMargin { get; set; }
        public int? CtintSwapMarginFormulaId { get; set; }
        public int? CtintMarginNotlPeriodFreq { get; set; }
        public bool? CtboolUseCpcurve { get; set; }
        public int? CtintDiscountCurveId { get; set; }
        public int? CtintFwdCurveId { get; set; }
        public int? CtintDiscSpreadCrvId { get; set; }
        public double? CtdblDiscCrvFixedSpread { get; set; }
        public int? CtintFwdRtSpreadCrvId { get; set; }
        public double? CtdblFwdRtCrvFixedSpread { get; set; }
        public bool CtblnUseDiscountCrvDf { get; set; }
        public bool CtblnUseFwdRateCrvDf { get; set; }
        public int? CtintCountriesId { get; set; }
        public bool Ctbool1099Exempt { get; set; }
        public int? CtintPledgeBucketId { get; set; }
        public int? CtintPledgeMarginMatrix { get; set; }
        public int? CtintPledgeMatrix { get; set; }
        public int? CtintDerivativeBucketId { get; set; }
        public int? CtintDerivativeMarginMatrix { get; set; }
        public bool CtblnDepositAgreement { get; set; }
        public bool CtblnDerivativeAgreement { get; set; }
        public int? CtintRepoSweepBucketId { get; set; }
        public int? CtintRepoSweepMarginMatrix { get; set; }
        public bool CtblnRepoSweepBalanceCalc { get; set; }
        public bool CtblnDerivateiveBalanceCalc { get; set; }
        public int? CtintCreditCurveId { get; set; }
        public bool CtblnIfema { get; set; }
        public DateTime? CtdtIsdaonFile { get; set; }
        public DateTime? CtdtIfemaonFile { get; set; }
        public double? CtdblCreditSpread { get; set; }
        public string SzGlobalIdentifier { get; set; }
        public bool CtblnSweepAgreement { get; set; }
        public DateTime? CtSweepAgreementDt { get; set; }
        public DateTime? CtlRepoAgreementDt { get; set; }
        public DateTime? CtDepositAgreementDt { get; set; }
        public DateTime? CtDerivativeAgreementDt { get; set; }
        public string CtstrDefaultCostCenterDg { get; set; }
        public int? CtintChartOfAccountIddg { get; set; }
        public bool CtblnInactive { get; set; }
        public DateTime? CtdtInactive { get; set; }
        public bool? CtboolProprietary { get; set; }
        public bool CtblnProcessAccountingMonthly { get; set; }
        public int? CtDayStartMonthlyProcessing { get; set; }
        public bool CtblnExcludeMonthlyProcess { get; set; }
        public bool CtboolUseBulletCashflow { get; set; }
        public string SQueryKey { get; set; }
        public int? CtintBranchResidencyId { get; set; }
    }
}
