using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace TTT_Practice.Models
{
    public partial class TblCusipMaster
    {
        public int CpintCusipMasterId { get; set; }
        public string CpstrCusip { get; set; }
        public DateTime? CpdateLastUpdated { get; set; }
        public string CpstrCusipCheckDsc { get; set; }
        public string CpstrAbsRefId { get; set; }
        public string CpstrPrefixDsc { get; set; }
        public string CpstrBankQualified { get; set; }
        public string CpstrPoolDsc { get; set; }
        public string CpstrShortDsc { get; set; }
        public string CpstrInfoLine1Dsc { get; set; }
        public string CpstrInfoLine2Dsc { get; set; }
        public string CpstrServicerId { get; set; }
        public bool CpboolDefaultedDsc { get; set; }
        public string CpstrStateIssuedInId { get; set; }
        public string CpstrIssuerId { get; set; }
        public DateTime CpdateIssuedDsc { get; set; }
        public decimal? CpsngIssueAmt { get; set; }
        public decimal? CpcurParValuePerShare { get; set; }
        public string CpstrCmoAcronym1Id { get; set; }
        public string CpstrCmoAcronym2Id { get; set; }
        public string CpstrCmoAcronym3Id { get; set; }
        public int? CpintCusipCollateralId { get; set; }
        public bool Payment { get; set; }
        public DateTime? CpdateBegLastAccrual { get; set; }
        public DateTime? CpdateCpnFirstPmt { get; set; }
        public double? CpdblNetWghtdAveCpnPmt { get; set; }
        public bool? CpboolFixedRate { get; set; }
        public double? CpdblServicingPctPmt { get; set; }
        public bool CpboolEom { get; set; }
        public byte CpintActualDelay { get; set; }
        public byte CpintDelayInMaty { get; set; }
        public bool Maturity { get; set; }
        public DateTime? CpdateStatedMaturityMty { get; set; }
        public bool CpboolEscrowedToMaturityMty { get; set; }
        public DateTime? CpdatePreRefundedMty { get; set; }
        public double? CpdblPreRefundedPriceMty { get; set; }
        public bool Callability { get; set; }
        public string CpstrOptionType { get; set; }
        public int? CpintOptionFrequency { get; set; }
        public byte? CpintCallTypeId { get; set; }
        public DateTime? CpdateFirstContinousCall { get; set; }
        public DateTime? CpdateLastContinousCall { get; set; }
        public short CpintNoticeDaysCall { get; set; }
        public DateTime? CpdateCallNoticeGiven { get; set; }
        public int CpintOptionCalendarConvId { get; set; }
        public bool Floater { get; set; }
        public short? CpintRateTypeId { get; set; }
        public DateTime? CpdateFirstResetFlt { get; set; }
        public int? CpintResetFreqFlt { get; set; }
        public short CpintResetBusDayConvId { get; set; }
        public short CpintResetHolidayListId { get; set; }
        public short CpintResetEomadjustId { get; set; }
        public short CpintRateLockDays { get; set; }
        public short CpintRateLockBusCalendarId { get; set; }
        public short CpintRateLockHolidayListId { get; set; }
        public double? CpdblPeriodicCapFlt { get; set; }
        public double? CpdblPeriodicFloorFlt { get; set; }
        public double? CpdblLifeCapFlt { get; set; }
        public double? CpdblLifeFloorFlt { get; set; }
        public double? CpdblTeaserFlt { get; set; }
        public bool CpboolRateOverride { get; set; }
        public int CpintStressTypeId { get; set; }
        public bool FloaterRateDtrm { get; set; }
        public int? CpintFormulaId { get; set; }
        public short? CpintRateRoundId { get; set; }
        public short? CpintRateRoundDecimal { get; set; }
        public bool UseEnteredRate { get; set; }
        public short CpintLookBackDays { get; set; }
        public short CpintLookBackBusCalendarId { get; set; }
        public short CpintLookBackBusDayConvId { get; set; }
        public short CpintLookBackHolidayListId { get; set; }
        public short? CpintIndex1IndicesId { get; set; }
        public short? CpintIndex1RoundId { get; set; }
        public short? CpintIndex1RoundDecimal { get; set; }
        public string CpstrIndex1Operator { get; set; }
        public double? CpdblIndex1Spread { get; set; }
        public bool CpboolIndex1MultiplySpread { get; set; }
        public double? CpdblIndex1Multiplier { get; set; }
        public short? CpintIndex2IndicesId { get; set; }
        public short? CpintIndex2RoundId { get; set; }
        public short? CpintIndex2RoundDecimal { get; set; }
        public string CpstrIndex2Operator { get; set; }
        public double? CpdblIndex2Spread { get; set; }
        public bool CpboolIndex2MultiplySpread { get; set; }
        public double? CpdblIndex2Multiplier { get; set; }
        public string CpstrIndexBetweenOperator { get; set; }
        public string OriginalAmortizeDtrm { get; set; }
        public string CpstrAmortizingWith { get; set; }
        public DateTime? CpdateAmortizeStart { get; set; }
        public DateTime? CpdateAmortizeStop { get; set; }
        public int? CpintAmortFreq { get; set; }
        public int? CpintAmortIndexId { get; set; }
        public short? CpintAmortIndexRoundId { get; set; }
        public short? CpintAmortIndexRoundAt { get; set; }
        public string CpstrAmortOper { get; set; }
        public double? CpdblAmortSpread { get; set; }
        public double? CpdblAmortIndexMultiplier { get; set; }
        public bool CpboolAmortSprdIncludeinMulti { get; set; }
        public short? CpintAmortLookbackDays { get; set; }
        public short? CpintAmortlkbDholidays { get; set; }
        public short? CpintAmortlkbDconvention { get; set; }
        public short? CpintAmortlkbDbusDayConv { get; set; }
        public double? CpdblCleanupCallPct { get; set; }
        public bool InstrumentsSettings { get; set; }
        public int? CpintHoldingTypeId { get; set; }
        public byte? CpintRcbclassId { get; set; }
        public byte CpintBloombergKeysId { get; set; }
        public string CpstrSector { get; set; }
        public string CpstrInvestCode { get; set; }
        public int? CpintGlgroupId { get; set; }
        public int CpintAlmgroupId { get; set; }
        public string CpstrDesc1 { get; set; }
        public string CpstrDesc2 { get; set; }
        public string CpstrPrefix { get; set; }
        public int CpintPaysInterestPerYearId { get; set; }
        public byte CpintPrincipalInterestTypeId { get; set; }
        public int? CpintPrincipalInterestScheduleId { get; set; }
        public bool CpboolBalloon { get; set; }
        public short? CpintStructuredId { get; set; }
        public int? CpintFqcyCompound { get; set; }
        public byte CpintCompoundTypesId { get; set; }
        public byte CpintDayCountId { get; set; }
        public byte CpintPmtBusDayConv { get; set; }
        public byte CpintpmtHolidaysListId { get; set; }
        public byte CpintPmtEopadjustId { get; set; }
        public short? CpintPricingFamilyId { get; set; }
        public string CpstrFamilyPrepayment { get; set; }
        public bool CpboolMultiFamilyMbs { get; set; }
        public short CpintCountriesId { get; set; }
        public short CpintCurrenciesId { get; set; }
        public byte CpintRiskWeightId { get; set; }
        public double CpdblRefinanceFee { get; set; }
        public string CpstrUserDef01 { get; set; }
        public decimal? CpintCleanupCallPct { get; set; }
        public string CpstrDefaultPxSourceId { get; set; }
        public bool Tax { get; set; }
        public bool CpboolFederallyTaxableTax { get; set; }
        public bool CpboolStateTaxableTax { get; set; }
        public double? CpdblOriginalIssueDiscountTax { get; set; }
        public bool CpboolRemicTax { get; set; }
        public byte? CpintUploadToBloomberg { get; set; }
        public byte? VisibleId { get; set; }
        public byte? ProcessableId { get; set; }
        public byte? ReportableId { get; set; }
        public byte? Zelect { get; set; }
        public string SLastUpdateId { get; set; }
        public DateTime? DtLastUpdateDt { get; set; }
        public short? IConcurrencyId { get; set; }
        public DateTime? Cpdatemtgadjdate { get; set; }
        public string Need2stress { get; set; }
        public int? CpintInflationIndexId { get; set; }
        public double? CpdblCollateralCpn { get; set; }
        public bool CpbitCallSchedule { get; set; }
        public bool CpboolIncludePayDateInPaymentAmount { get; set; }
        public bool CpboolApplyRateToEntirePeriod { get; set; }
        public DateTime? CpsdtIssuedDate { get; set; }
        public bool? CpboolAccrualonPar { get; set; }
        public string CpstrIsin { get; set; }
        public string CpstrSedol { get; set; }
        public string SzExchangeCode { get; set; }
        public bool? DvboolAmount { get; set; }
        public int? CpintPrincipalPaymentDelay { get; set; }
        public DateTime? CpdtFirstPrincipalPayment { get; set; }
        public int? CpintPrincipalPaymentFreq { get; set; }
        public int CpintIncludePayDateInPaymentAmount { get; set; }
        public string CpszConvertible { get; set; }
        public string CpszArmSubType { get; set; }
        public string CpszCollatType { get; set; }
        public string CpszTrancheType { get; set; }
        public double? CpdblGrossMgn { get; set; }
        public string CpszNextResetMonths { get; set; }
        public string CpszOriginatorServicer { get; set; }
        public string CpszCreditEnhancements { get; set; }
        public int? CpintObligorId { get; set; }
        public string CpszGuarantor { get; set; }
        public int? CplGuarantorCountryId { get; set; }
        public string CpszIssuerIndustry { get; set; }
        public int? CpintCountriesIdofRisk { get; set; }
        public int? CpintCountriesIdofDomicile { get; set; }
        public string CpstrBbgid { get; set; }
        public int? CpiDelayDayConventionId { get; set; }
        public int? CpintAccrBusDayConv { get; set; }
        public int? CpintAccrHolidaysListId { get; set; }
        public int? CpintFixingLag { get; set; }
        public int? CpintFixingHolidayListId { get; set; }
        public bool CpblnIncludeStart { get; set; }
        public bool CpblnIncludeEnd { get; set; }
        public bool CpblnFrontPay { get; set; }
        public int? CpintFixingBusDayConvId { get; set; }
        public bool CpblnFdichighSecuritization { get; set; }
        public decimal? CpcurLotsize { get; set; }
        public bool CpblnPayDatesOverridden { get; set; }
        public string CpstrBorrower { get; set; }
        public string CpstrGuarantor { get; set; }
        public decimal? CpLoanCommitment { get; set; }
        public decimal? CpUnfundedLoanCommitment { get; set; }
        public int? CpintPerformanceStatus { get; set; }
        public int? CpintServicingStatus { get; set; }
        public int? CpintAccrualStatus { get; set; }
        public int? CpintImpairmentStatus { get; set; }
        public int? CpintChargeOffStatus { get; set; }
        public decimal? CpChargeOffBalance { get; set; }
        public decimal? CpPrincipalSold { get; set; }
        public string CpstrPurpose { get; set; }
        public string CpstrType { get; set; }
        public string CpstrBookrunners { get; set; }
        public string CpstrCoLeadArranger { get; set; }
        public string CpstrAgent { get; set; }
        public string CpstrLender { get; set; }
        public string CpstrProjectSponsor { get; set; }
        public string CpstrLegalAdvisor { get; set; }
        public decimal? CpFaceAmount { get; set; }
        public decimal? CpTransferFee { get; set; }
        public int? CpintEstimatedAccrued { get; set; }
        public decimal? CpPayableBuyer { get; set; }
        public decimal? CpPayableSeller { get; set; }
        public decimal? CpNetAmountPayable { get; set; }
        public string CpstrOriginalLtv { get; set; }
        public string CpstrAdjustedLtv { get; set; }
        public int? CpintRefiNew { get; set; }
        public int? CpintPropertyType { get; set; }
        public int? CpintOccupancy { get; set; }
        public DateTime? CpdateTdr { get; set; }
        public DateTime? CpdateOriginalFundingDate { get; set; }
        public DateTime? CpdateModifiedFundingDate { get; set; }
        public string CpstrDscr { get; set; }
        public string CpstrDssrexpRatio { get; set; }
        public string CpstrCurrentRatio { get; set; }
        public string CpstrRetainedEarnings { get; set; }
        public DateTime? CpdateFirstPrincipal { get; set; }
        public int? CpintPrincFrequency { get; set; }
        public int? CpintIntFrequency { get; set; }
        public decimal? CpMargin { get; set; }
        public bool? CpboolRateStubInterest { get; set; }
        public DateTime? CpdateRateStubInterest { get; set; }
        public int? CpintAmortType { get; set; }
        public int? CpintAmortTerm { get; set; }
        public int? CpintLoanTerm { get; set; }
        public int? CpintIoperiod { get; set; }
        public bool? CpboolAmortStubInterest { get; set; }
        public DateTime? CpdateAmortStubInterest { get; set; }
        public decimal? CpStubAmortInterestAmount { get; set; }
        public DateTime? CpdtFirstSettlement { get; set; }
        public decimal? CpStubRateInterestAmount { get; set; }
    }
}
