using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace TTT_Practice.Models
{
    public partial class TblSwaps
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AccountingNumber { get; set; }
        public int DerivativeTypesId { get; set; }
        public string Description { get; set; }
        public DateTime Trade { get; set; }
        public DateTime Effective { get; set; }
        public DateTime Settlement { get; set; }
        public DateTime? FirstCall { get; set; }
        public DateTime? LastCall { get; set; }
        public DateTime Maturity { get; set; }
        public byte SettlementHolidayListId { get; set; }
        public decimal NotionalOrigAmt { get; set; }
        public int CounterPartyId { get; set; }
        public int WiringInstructionsId { get; set; }
        public string CntrprtysSwapId { get; set; }
        public int CallFrequenciesId { get; set; }
        public short CallEomadjust { get; set; }
        public short CallNotifyDays { get; set; }
        public byte CallNotificationId { get; set; }
        public decimal CleanupCallPct { get; set; }
        public int CustomerSetupId { get; set; }
        public byte VisibleId { get; set; }
        public byte ProcessableId { get; set; }
        public byte ReportableId { get; set; }
        public byte? Zelect { get; set; }
        public int IntDefaultAmortizationType { get; set; }
        public int IntDefaultSetting { get; set; }
        public int IntAmortMethodId { get; set; }
        public bool Futures { get; set; }
        public double? LContractsQty { get; set; }
        public double DblPrice { get; set; }
        public int? LMonthContractId { get; set; }
        public bool Options { get; set; }
        public int LOptionStyleId { get; set; }
        public double DblStrikePx { get; set; }
        public DateTime DtLastUpdateDt { get; set; }
        public int LHoldingTypeId { get; set; }
        public short LDrvInstrumentId { get; set; }
        public byte LInstrumentGroupsMajor { get; set; }
        public byte LPrincipalExchangedId { get; set; }
        public bool BoolMargin { get; set; }
        public byte LExchangeId { get; set; }
        public string SLastUpdateId { get; set; }
        public short? IConcurrencyId { get; set; }
        public DateTime? DtmCreateDt { get; set; }
        public string ChrCreateUser { get; set; }
        public DateTime? DtmTermDt { get; set; }
        public DateTime? DtmModifyDt { get; set; }
        public string ChrModifyUser { get; set; }
        public int? OffsetSwapId { get; set; }
        public int? StrAcctDesignation { get; set; }
        public string StrUserDefined1 { get; set; }
        public string StrUserDefined2 { get; set; }
        public string StrUserDefined3 { get; set; }
        public string StrUserDefined4 { get; set; }
        public string StrUserDefined5 { get; set; }
        public string StrUserDefined6 { get; set; }
        public string StrDefaultPxSourceId { get; set; }
        public string StrMonthYearCode { get; set; }
        public short LLongShortId { get; set; }
        public short LCallPutId { get; set; }
        public double DblParticipationRate { get; set; }
        public decimal? MnyPremium { get; set; }
        public bool? BlnCallFrontStub { get; set; }
        public bool? BlnCallLongStub { get; set; }
        public bool? BlnCallArrearsReset { get; set; }
        public bool? BlnCallIncludeStart { get; set; }
        public bool? BlnCallIncludeEnd { get; set; }
        public bool? BlnCallFrontPay { get; set; }
        public int? LCallAccrualCalendar { get; set; }
        public int? LCallAccrualConvention { get; set; }
        public int? LCallFixCalendar { get; set; }
        public int? LCallPayCalendar { get; set; }
        public int? LCallPayConvention { get; set; }
        public string StrOptionTransType { get; set; }
        public DateTime? DtmOptionExcerciseDate { get; set; }
        public int? LOptionSpotLag { get; set; }
        public int? LOptionSpotCalendar { get; set; }
        public string StrOptionSwapTenor { get; set; }
        public int? LOptionFrequency { get; set; }
        public int? LOptionBasis { get; set; }
        public int? LOptionAccrualCalendar { get; set; }
        public int? LOptionAccrualConvention { get; set; }
        public bool? BlnOptionNormalVol { get; set; }
        public DateTime? DtmOptionSettlement { get; set; }
        public int? LCallFixConvention { get; set; }
        public double? DblSigma { get; set; }
        public int? IntDiscCrvSpreadId { get; set; }
        public double? DblDiscCrvFixedSpread { get; set; }
        public int? IntFwdRtCrvSpreadId { get; set; }
        public double? DblFwdRtCrvFixedSpread { get; set; }
        public int? LRepoPositionId { get; set; }
        public int LTraderId { get; set; }
        public DateTime? DtEnteredAsOf { get; set; }
        public double? DblMarginPercent { get; set; }
        public int? LMarginFormulaId { get; set; }
        public int? LMarginNotlPeriodFreq { get; set; }
        public DateTime? DtOptionStart { get; set; }
        public DateTime? DtOptionEnd { get; set; }
        public bool? BitSettleDate { get; set; }
        public DateTime? DtCancelDate { get; set; }
        public bool? BitCancelDate { get; set; }
        public int? LFxswapTransId { get; set; }
        public string StrReasonToTrade { get; set; }
        public double? DblCommisionPerContract { get; set; }
        public decimal? CurCommisionAmount { get; set; }
        public int? ContactId { get; set; }
        public bool? UseBlack76PricingModel { get; set; }
        public int? LCapVolInterpMethod { get; set; }
        public int? LCapVolInterpVariable { get; set; }
        public int? LCapVolFixCalendar { get; set; }
        public int? LCapVolExtrapMethod { get; set; }
        public int? LCapVolPayCalendar { get; set; }
        public int? LCapVolBusDayConv { get; set; }
        public int? LCapVolCapBasis { get; set; }
        public int? LCapVolVolatilityBasis { get; set; }
        public int? LCapVolNoticePeriod { get; set; }
        public DateTime? DtBarrierFirstResetDate { get; set; }
        public int? LBarrierResetFrequenciesId { get; set; }
        public int? LBarrierResetBusDayConvId { get; set; }
        public int? LBarrierResetHolidayListId { get; set; }
        public int? LBarrierResetEomadjustId { get; set; }
        public double? DblBarrierRate { get; set; }
        public int? LMonthYearCodeId { get; set; }
        public bool BlnExcludeFromProcessing { get; set; }
        public int? FarFxswapTransId { get; set; }
        public int? IntStatus { get; set; }
        public int? StrategyId { get; set; }
        public bool BlnTraderPending { get; set; }
        public bool BlnDgtmp { get; set; }
        public int? LApprovalId { get; set; }
        public bool BlnAtm { get; set; }
        public string SzSwapGlobalIdentifier { get; set; }
        public int? CallBusDayConvId { get; set; }
        public int? LRevRepoPositionId { get; set; }
        public int? ITransactionCode { get; set; }
        public double DblShare { get; set; }
        public int? IFcm { get; set; }
        public int? ICcp { get; set; }
        public double? Fxrate { get; set; }
        public int? ValuationCurrency { get; set; }
        public decimal? ValuationNotional { get; set; }
        public double? MarginPerContract { get; set; }
        public int? IMultiTradeId { get; set; }
        public bool ResetNotional { get; set; }
    }
}
